### ISSUE TITLE
Feasability of adding RAM expansion to the board?

### ISSUE THREAD

**Issue by Lalarian** [LemaruX/Amiga-A600-68k-PLCC2DIP-v2#2]
Hello!
I was just searching on how to make my A600 a bit more fun, in speed and maybe WHDLoad-capabilities, without paying a fortune. Your project is the most interesting, because the option for adding an 68010 on the A600 not only gives a (tiny) bit more speed, but also enables to use the WHDLoad quit-key feature.
Of course we still need FastRAM, for this to actually be of much use for WHDLoad and getting most of the 68010.
As there currently is a gap of about 100€ between pure FastRAM expansions and the cheapest full Turbocards, I was searching for simple FastRAM expansions.
I was checking the SukkoPera's FatRAM expansion for the A500 and though I could place it on top of your adapter.  But then, SukoPerra's A600 expansion doesn't add an 68010...

Next I though: Why fiddle around with two boards, having an even more fragile system, more soldering work, or having to buy more cards than one.
So: 
Would it be possible for you (or too much work? / Too expensive?) to add the option for 4 or 8 MB FastRAM to the board?

Thank you for your contribution to the Amiga! :)

**Comment by LemaruX** [comment]
Hi,

That is possible to do, space maybe a bit of an issue to keep it compact. I have something in mind and may look into coming up with something, but need to find time to do it. 

I'll add it to my to-do list. 

I think Kipper2k may actually have already designed something similar for use with Buffee, but hasn't yet released it. So that is another option. 

Thanks

**Comment by Lalarian** [comment]
I think you! :)
